sparsehash requires SSE4.1 instructions
The following unpleasant error is fixed on machines that do not by default enable SSE4.1 on GCC.

``In file included from gssw/src/gssw.h:19:0,
                 from gssw_aligner.hpp:7,
                 from gssw_aligner.cpp:1:
/usr/lib64/gcc/x86_64-suse-linux/4.8/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled"
 # error "SSE4.1 instruction set not enabled"
   ^
In file included from gssw_aligner.hpp:7:0,
                 from gssw_aligner.cpp:1:
``